name: "#Check Build Solution"

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - src/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        working-directory: src
        run: dotnet restore

      - name: Build
        working-directory: src
        run: dotnet build --configuration Release --no-restore
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        working-directory: src
        run: dotnet restore
        
      - name: Test
        working-directory: src
        run: dotnet test