name: "Run Performance Tests"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        working-directory: src/Menaver.NetBitSet.Tests.Perf
        run: dotnet restore

      - name: Build
        working-directory: src/Menaver.NetBitSet.Tests.Perf
        run: dotnet build --configuration Release --no-restore
        
      - name: Test
        working-directory: src/Menaver.NetBitSet.Tests.Perf
        run: dotnet run --configuration Release